language: go
go_import_path: github.com/etf1/health-check
go:
  - 1.x

sudo: false

before_install:
  - docker-compose -f docker/docker-compose-test.yaml up -d

install:
  - go get -u github.com/golang/dep/cmd/dep && dep ensure -vendor-only -v

before_script:
  - export HEALTH_GO_REDIS_PROXY_ADDR="`docker-compose -f docker/docker-compose-test.yaml port twem-proxy 6380`"
  - export HEALTH_GO_REDIS_ADDR="`docker-compose -f docker/docker-compose-test.yaml port redis-a 6379`"
  - export HEALTH_GO_POSTGRES_ADDR="postgres://test:test@`docker-compose -f docker/docker-compose-test.yaml port postgres 5432`/test?sslmode=disable"

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
