language: go
go_import_path: github.com/etf1/healthcheck
go:
  - 1.*

sudo: false

before_install:
  - docker-compose -f docker/docker-compose-test.yaml up -d

install:
  - go get -u github.com/golang/dep/cmd/dep && dep ensure -vendor-only -v

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
