[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
